FROM node:lts-alpine AS builder

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add git

COPY . /app

RUN npm install
RUN npm run build

# start final image
FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app /app

ENV NUXT_HOST=0.0.0.0
EXPOSE 3000

ENTRYPOINT ["node", ".output/server/index.mjs"]